USE blog_hexalud_DB;

INSERT INTO entradas_blog (titulo, autor, contenido)
VALUES
    ('Me duele la espalda', 'Alejandro Larios', 'No se que esta pasando pero me duele la espalda y. quiero que me digan que puedo hacer o si ya vali jajajaja'),
    ('Me duele la espalda recargado', 'Alexi Larios', 'Mi espalda está en huelga, exige mejores condiciones de descanso. Está tan dramática que ya le compuse una canción triste: ''El blues de la columna vertebral''. ¡Espero que mi fisioterapeuta tenga sentido del humor! 😅 #EspaldaEnProtesta'),
    ('La odisea de los calcetines perdidos', 'Risitas McChistes', 'Mis calcetines tienen una vida propia. Cada vez que lavo la ropa, algunos deciden hacer una escapada misteriosa. Me pregunto si están de vacaciones o simplemente se rebelaron. ¡Necesito un detective para resolver este enigma doméstico! 🕵️‍♂️😂'),
    ('La filosofía de los aguacates maduros', 'Cómico Filósofo', 'Reflexionando sobre la vida mientras espero que mi aguacate madure. ¿Acaso la paciencia es la clave del buen guacamole? O tal vez, el aguacate nos enseña que la madurez llega en el momento perfecto, al igual que las mejores cosas de la vida. ¡Aguacate, maestro zen en la cocina! 🥑🤔😆'),
    ('El arte de llegar tarde con estilo', 'Inventor de Excusas', 'Llegar tarde es un arte que requiere práctica y creatividad. Hoy, mi excusa fue que mi despertador y yo tuvimos una discusión filosófica sobre el tiempo. Al final, ganó el tiempo relativo. ¡La próxima vez, consideraré la puntualidad como una opción viable! ⏰🎨😄'),
    ('Viaje al fondo de la nevera', 'Explorador de Nevera', 'Hoy me aventuré al fondo de mi nevera en busca de la cena perdida. Descubrí un ecosistema desconocido, donde los envases expirados eran ruinas antiguas y las verduras olvidadas eran tesoros escondidos. ¡Una expedición culinaria épica que terminó en pizza congelada! 🍕🧳😂'),
    ('La tragedia del último trozo de pizza', 'Gastrónomo Cómico', 'En el drama culinario de mi vida, el último trozo de pizza sufre una soledad desgarradora en la nevera. Nadie se atreve a comerlo, todos lo miran con nostalgia. Es como la última escena de una película triste, pero más deliciosa. ¡Que alguien lo salve antes de que se convierta en una reliquia! 🍕😢😋'),
    ('El misterio de las pantuflas desaparecidas', 'Soñador de Pantuflas', 'Cada noche, coloco mis pantuflas juntas, pero al despertar, una siempre está en una búsqueda épica por la casa. ¿Se escapan para vivir aventuras nocturnas? ¿O simplemente tienen problemas de orientación? Tal vez, debería contratar a un detective de calzado para resolver este enigma acogedor. 🕵️‍♂️🥿🌙'),
    ('La consulta del hipo persistente', 'Doctor Rimas', 'Un paciente vino con un caso serio: hipo persistente. Tras múltiples intentos de asustarlo, sorprenderlo y hasta darle un susto virtual, el hipo seguía firme. Diagnosticé ''hiposis aguda''. Receté risas, una película cómica y una cucharada de azúcar. ¡La risa es el mejor remedio! 😄💉👨‍⚕️'),
    ('Donde estoy?', 'Chico del Pórtico', 'Desperté con confusión en un lugar extraño. El GPS se rindió y mi sentido de la orientación también. Entre callejones y portales misteriosos, me pregunto si caí en un portal dimensional o simplemente descubrí una nueva versión de Google Maps. ¡Aventura inesperada o desorientación total? 🌐🤷‍♂️😂'),
    ('La épica batalla del control remoto', 'Dramaturgo Doméstico', 'En el épico conflicto del sofá, el control remoto y yo luchamos por el dominio. Es una guerra remota, donde los canales son campos de batalla y los programas son estrategias de ataque. Al final, ambos quedamos exhaustos, pero ninguno cede. ¡Una historia digna de un Emmy doméstico! 📺🤺😅'),
    ('El experimento gastronómico de la tostadora', 'Científico Culinario', 'Hoy decidí desafiar las leyes de la cocina y convertir mi tostadora en un laboratorio culinario. Intenté tostar malvaviscos, hacer mini pizzas y hasta gratinar macarrones con queso. Mi cocina se convirtió en un campo de pruebas inusual. ¡Quién dijo que la tostadora solo sirve para tostar pan! 🍞🔬😂'),
    ('El que se fue a la Villa', 'Rogelio Ramirez', 'Había una vez un aventurero que decidió abandonar la ciudad y mudarse a una villa tranquila. Soñaba con campos verdes y aire fresco. Sin embargo, la realidad lo golpeó: las vacas eran vecinas ruidosas y el wifi era más lento que una tortuga. Se dio cuenta de que, a veces, la villa ideal solo existe en los cuentos de hadas urbanos. 🌳🏡😆'),
    ('El gran Vaquero', 'Kenji Sashida', 'En el polvoriento pueblo de Polvorín, vivía ''El Gran Vaquero'', famoso por contar historias más grandes que su sombrero. Decían que su risa hacía temblar hasta los cactus y que su caballo bailaba al ritmo de sus cuentos. Una vez, narró una historia tan larga que el sol se puso antes de que terminara. ¡En Polvorín, nadie se quedaba sin escuchar al Gran Vaquero! 🤠📜😂');
